
GET http://localhost:5186/games

###
GET http://localhost:5186/games/3

###
POST http://localhost:5186/games
Content-Type: application/json

{
    "Name":"Minecraft",
    "Genre":"Kids and  Family",
    "Price":19.99,
    "ReleaseDate":"2011-11-18"
}

###
PUT http://localhost:5186/games/1
Content-Type: application/json

{
    "Name":"StreetFighter II Turbo",
    "Genre":"Fighting",
    "Price":9.99,
    "ReleaseDate":"1992-07-15"
}

###
DELETE http://localhost:5186/games/2